name: uv

on:
  push:
    branches:
      - main

jobs:
  print-hello:
    name: uv
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync

#      - name: Run hello
#        run: uv run just_one_sql/hello.py
